[I 2023-10-29 16:12:55.670 ServerApp] Package notebook took 0.0000s to import
[I 2023-10-29 16:12:55.690 ServerApp] Package jupyter_lsp took 0.0193s to import
[W 2023-10-29 16:12:55.690 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-29 16:12:55.699 ServerApp] Package jupyter_server_terminals took 0.0084s to import
[I 2023-10-29 16:12:55.700 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-10-29 16:12:56.054 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-10-29 16:12:56.055 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-29 16:12:56.057 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-10-29 16:12:56.062 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-10-29 16:12:56.066 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-10-29 16:12:56.071 ServerApp] notebook | extension was successfully linked.
[I 2023-10-29 16:12:56.419 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-10-29 16:12:56.444 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-10-29 16:12:56.454 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-10-29 16:12:56.456 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-10-29 16:12:56.461 LabApp] JupyterLab extension loaded from /home/johndym/.local/lib/python3.10/site-packages/jupyterlab
[I 2023-10-29 16:12:56.461 LabApp] JupyterLab application directory is /home/johndym/.local/share/jupyter/lab
[I 2023-10-29 16:12:56.462 LabApp] Extension Manager is 'pypi'.
[I 2023-10-29 16:12:56.465 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-10-29 16:12:56.467 ServerApp] notebook | extension was successfully loaded.
[I 2023-10-29 16:12:56.469 ServerApp] Serving notebooks from local directory: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv
[I 2023-10-29 16:12:56.470 ServerApp] Jupyter Server 2.8.0 is running at:
[I 2023-10-29 16:12:56.470 ServerApp] http://localhost:8888/tree?token=66b8e9a38923b8d3d75bf37ae84a246826e6bab83a96ec76
[I 2023-10-29 16:12:56.471 ServerApp]     http://127.0.0.1:8888/tree?token=66b8e9a38923b8d3d75bf37ae84a246826e6bab83a96ec76
[I 2023-10-29 16:12:56.471 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-10-29 16:12:59.764 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/johndym/.local/share/jupyter/runtime/jpserver-694-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=66b8e9a38923b8d3d75bf37ae84a246826e6bab83a96ec76
        http://127.0.0.1:8888/tree?token=66b8e9a38923b8d3d75bf37ae84a246826e6bab83a96ec76
[I 2023-10-29 16:13:02.069 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2023-10-29 16:13:21.915 ServerApp] Kernel started: 6d357f04-5e5b-4fb3-8ab5-7f49b3beeaa1
[I 2023-10-29 16:13:22.569 ServerApp] Connecting to kernel 6d357f04-5e5b-4fb3-8ab5-7f49b3beeaa1.
[I 2023-10-29 16:15:21.661 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 16:31:21.871 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 19:34:39.548 ServerApp] Starting buffering for 6d357f04-5e5b-4fb3-8ab5-7f49b3beeaa1:4e107e73-4440-4776-9291-388aa579a9b4
[I 2023-10-29 21:51:16.856 ServerApp] Package notebook took 0.0000s to import
[I 2023-10-29 21:51:16.870 ServerApp] Package jupyter_lsp took 0.0131s to import
[W 2023-10-29 21:51:16.870 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-29 21:51:16.876 ServerApp] Package jupyter_server_terminals took 0.0052s to import
[I 2023-10-29 21:51:16.877 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-10-29 21:51:17.160 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-10-29 21:51:17.160 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-29 21:51:17.162 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-10-29 21:51:17.167 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-10-29 21:51:17.172 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-10-29 21:51:17.177 ServerApp] notebook | extension was successfully linked.
[I 2023-10-29 21:51:17.440 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-10-29 21:51:17.458 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-10-29 21:51:17.469 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-10-29 21:51:17.471 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-10-29 21:51:17.473 LabApp] JupyterLab extension loaded from /home/johndym/.local/lib/python3.10/site-packages/jupyterlab
[I 2023-10-29 21:51:17.473 LabApp] JupyterLab application directory is /home/johndym/.local/share/jupyter/lab
[I 2023-10-29 21:51:17.474 LabApp] Extension Manager is 'pypi'.
[I 2023-10-29 21:51:17.477 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-10-29 21:51:17.480 ServerApp] notebook | extension was successfully loaded.
[I 2023-10-29 21:51:17.480 ServerApp] The port 8888 is already in use, trying another port.
[I 2023-10-29 21:51:17.481 ServerApp] Serving notebooks from local directory: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv
[I 2023-10-29 21:51:17.482 ServerApp] Jupyter Server 2.8.0 is running at:
[I 2023-10-29 21:51:17.482 ServerApp] http://localhost:8889/tree?token=728cecf8963fe8bb59dcbc362adc34ba24a7c344066ca959
[I 2023-10-29 21:51:17.483 ServerApp]     http://127.0.0.1:8889/tree?token=728cecf8963fe8bb59dcbc362adc34ba24a7c344066ca959
[I 2023-10-29 21:51:17.483 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-10-29 21:51:20.705 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/johndym/.local/share/jupyter/runtime/jpserver-8545-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/tree?token=728cecf8963fe8bb59dcbc362adc34ba24a7c344066ca959
        http://127.0.0.1:8889/tree?token=728cecf8963fe8bb59dcbc362adc34ba24a7c344066ca959
[I 2023-10-29 21:51:23.565 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-10-29 21:51:35.142 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612695136 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:35.143 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:51:35.156 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612695136 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 14.59ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:51:36.143 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:36.164 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 21.09ms referer=None
[W 2023-10-29 21:51:36.171 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612696164 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:36.171 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:51:36.172 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612696164 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.52ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:51:39.133 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:39.135 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.64ms referer=None
[W 2023-10-29 21:51:39.139 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612699136 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:39.140 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:51:39.141 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612699136 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.18ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:51:46.134 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:46.136 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.11ms referer=None
[W 2023-10-29 21:51:46.140 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612706136 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:46.141 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:51:46.142 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612706136 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.00ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:51:54.142 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:54.143 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.00ms referer=None
[W 2023-10-29 21:51:54.147 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612714143 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:51:54.148 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:51:54.149 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612714143 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 2.18ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:52:07.059 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612726838 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:07.060 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:07.091 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612726838 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 111.30ms referer=http://localhost:8889/tree
[W 2023-10-29 21:52:08.835 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612728769 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:08.836 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:08.837 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612728769 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 66.00ms referer=http://localhost:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:52:17.152 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:52:17.156 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 5.48ms referer=None
[W 2023-10-29 21:52:17.166 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612737157 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:52:17.167 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:52:17.169 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612737157 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 4.84ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:52:22.013 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612741965 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:22.014 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:22.014 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612741965 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 46.03ms referer=http://localhost:8889/tree
[W 2023-10-29 21:52:23.155 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:52:23.160 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e/channels?session_id=24814c6a-9287-4913-8546-b9ff61ae8934 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 6.30ms referer=None
[W 2023-10-29 21:52:23.173 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612743164 (127.0.0.1): Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e
[W 2023-10-29 21:52:23.174 ServerApp] wrote error: 'Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f70f25ed-1709-45ca-a1bc-11361dfc7f6e)
[W 2023-10-29 21:52:23.176 ServerApp] 404 GET /api/kernels/f70f25ed-1709-45ca-a1bc-11361dfc7f6e?1698612743164 (190b05f8c26c4bb79fb44e5f1ca8a026@127.0.0.1) 3.85ms referer=http://127.0.0.1:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:52:23.616 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612743565 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:23.616 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:23.617 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612743565 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 49.29ms referer=http://localhost:8889/notebooks/EDA_report.ipynb
[W 2023-10-29 21:52:46.556 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612766512 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:46.557 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:46.558 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612766512 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 44.03ms referer=http://localhost:8889/tree
[W 2023-10-29 21:52:48.209 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612768150 (127.0.0.1): Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 2023-10-29 21:52:48.210 ServerApp] wrote error: 'Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "m...\')'
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 828, in _notebook_model
        nb = await self._read_notebook(
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 387, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...'))
[W 2023-10-29 21:52:48.211 ServerApp] 400 GET /api/contents/EDA_report.ipynb?type=notebook&content=1&1698612768150 (fe62369e8d2d49b9b18c2441e6c7cc57@127.0.0.1) 56.95ms referer=http://localhost:8889/notebooks/EDA_report.ipynb
[I 2023-10-29 21:53:39.069 ServerApp] Kernel started: 83af35fd-85de-47e6-af5a-11f40fbf1858
[I 2023-10-29 21:53:39.914 ServerApp] Connecting to kernel 83af35fd-85de-47e6-af5a-11f40fbf1858.
[W 2023-10-29 21:59:04.128 ServerApp] Unknown error checking if file '/mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report (2).ipynb' is hidden
    Traceback (most recent call last):
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 770, in _dir_model
        contents.append(await self.get(path=f"{path}/{name}", content=False))
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 875, in get
        model = await self._notebook_model(path, content=content)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 822, in _notebook_model
        model = self._base_model(path)
      File "/home/johndym/.local/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 226, in _base_model
        info = os.lstat(os_path)
    FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/fmojt/Documents/school/IAU/.virenv/EDA_report (2).ipynb'
[I 2023-10-29 21:59:08.209 ServerApp] Starting buffering for 83af35fd-85de-47e6-af5a-11f40fbf1858:2d093d70-635f-4187-ae82-472b30caa415
/home/johndym/.local/lib/python3.10/site-packages/nbformat/__init__.py:93: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
[W 2023-10-29 21:59:09.618 ServerApp] Notebook EDA_report.ipynb is not trusted
[W 2023-10-29 21:59:11.960 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 21:59:12.280 ServerApp] Connecting to kernel 83af35fd-85de-47e6-af5a-11f40fbf1858.
[I 2023-10-29 22:01:12.158 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:01:12.160 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:03:12.356 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:03:12.357 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:05:12.545 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:05:12.547 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:07:12.783 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:07:12.785 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:09:12.967 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:09:12.968 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:11:13.179 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:11:13.180 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:13:13.402 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:13:13.404 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:15:13.653 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:15:13.655 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:17:13.809 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:17:13.810 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:19:13.983 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:19:13.984 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:21:14.152 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:23:14.393 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:25:14.621 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:27:14.866 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:29:15.123 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:31:15.300 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:33:15.511 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:35:15.751 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:37:15.970 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:43:16.200 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:45:16.418 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:47:16.610 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:47:54.569 ServerApp] Kernel started: cfea9b81-9324-43fb-b345-d85668c2392d
[I 2023-10-29 22:47:55.249 ServerApp] Connecting to kernel cfea9b81-9324-43fb-b345-d85668c2392d.
[I 2023-10-29 22:48:33.261 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:48:33.264 ServerApp] Notebook EDA_report.ipynb is not trusted
[I 2023-10-29 22:48:34.464 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 22:48:34.465 ServerApp] Notebook EDA_report.ipynb is not trusted
[W 2023-10-29 22:48:34.583 ServerApp] /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/.~EDA_report.ipynb doesn't exist
[I 2023-10-29 22:49:03.333 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:49:04.853 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:51:05.033 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:53:05.220 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 22:59:05.477 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:01:05.757 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:03:05.983 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:05:06.270 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:07:06.483 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:09:06.710 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:11:06.922 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:13:07.121 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:14:53.022 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 23:14:53.181 ServerApp] /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/.~EDA_report.ipynb doesn't exist
[I 2023-10-29 23:15:00.004 ServerApp] Kernel restarted: 83af35fd-85de-47e6-af5a-11f40fbf1858
[I 2023-10-29 23:15:00.010 ServerApp] Starting buffering for 83af35fd-85de-47e6-af5a-11f40fbf1858:863da288-0ff2-4298-915d-1254d59472f6
[I 2023-10-29 23:15:00.021 ServerApp] Connecting to kernel 83af35fd-85de-47e6-af5a-11f40fbf1858.
[I 2023-10-29 23:15:00.022 ServerApp] Restoring connection for 83af35fd-85de-47e6-af5a-11f40fbf1858:863da288-0ff2-4298-915d-1254d59472f6
[I 2023-10-29 23:16:53.254 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 23:16:53.400 ServerApp] /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/.~EDA_report.ipynb doesn't exist
[I 2023-10-29 23:18:53.494 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:20:53.692 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:22:16.350 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 23:22:16.504 ServerApp] /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/.~EDA_report.ipynb doesn't exist
[I 2023-10-29 23:22:28.527 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:22:29.402 ServerApp] Saving file at /EDA_report.ipynb
[W 2023-10-29 23:22:29.568 ServerApp] /mnt/c/Users/fmojt/Documents/school/IAU/.virenv/.~EDA_report.ipynb doesn't exist
[I 2023-10-29 23:22:29.993 ServerApp] Saving file at /EDA_report.ipynb
[I 2023-10-29 23:22:30.921 ServerApp] Starting buffering for 83af35fd-85de-47e6-af5a-11f40fbf1858:863da288-0ff2-4298-915d-1254d59472f6
[I 2023-10-29 23:22:39.810 ServerApp] Starting buffering for cfea9b81-9324-43fb-b345-d85668c2392d:18b489e0-ae49-4c01-9676-1ef830d7a59c
